apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    job-refactor.sre.rootcloud.info/comparison-content: image
  labels:
    app.oam.dev/revision: test-job-v1
  name: test-job-latest
  namespace: default
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-job
        app.oam.dev/component: test-job
        job-name: test-job-latest
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          echo default
          sleep 10
        #image: dockerhub.tencentcloudcr.com/library/nginx:alpine
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: test-job
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 900
