apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    sre-mutator.rootcloud.info/job-recreate-reason: image
  labels:
    app.oam.dev/revision: test-job-v3
  name: test-job-latest
  namespace: default
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-job
        app.oam.dev/component: test-job
        job-name: test-job-latest
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          echo $k2
          sleep 10
        env:
        - name: k1
          value: v1 
        - name: k2
          value: v3
        #image: dockerhub.tencentcloudcr.com/library/nginx:stable
        image: nginx:stable
        imagePullPolicy: IfNotPresent
        name: test-job
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 900
