apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default

patches:
  - patch: |
      - op: "add"
        path: "/webhooks/0/clientConfig/url"
        value: "https://host.docker.internal:9443/mutate-core-v1-pod"
    target:
      kind: MutatingWebhookConfiguration
  - patch: |
      - op: "add"
        path: "/webhooks/0/clientConfig/url"
        value: "https://host.docker.internal:9443/mutate-core-v1-pod"
    target:
      kind: ValidatingWebhookConfiguration
  - path: webhook_patch.yaml
    target:
      group: admissionregistration.k8s.io