apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hostaliases-injector.fullname" . }}-manager-role
  labels:
  {{- include "hostaliases-injector.labels" . | nindent 4 }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hostaliases-injector.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hostaliases-injector
    app.kubernetes.io/part-of: hostaliases-injector
  {{- include "hostaliases-injector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "hostaliases-injector.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "hostaliases-injector.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'