apiVersion: v1
kind: Service
metadata:
  name: {{ include "hostaliases-injector.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: hostaliases-injector
    app.kubernetes.io/part-of: hostaliases-injector
    control-plane: controller-manager
  {{- include "hostaliases-injector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "hostaliases-injector.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}