apiVersion: v1
kind: Service
metadata:
  name: {{ include "sre-mutator.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: sre-mutator
    app.kubernetes.io/part-of: sre-mutator
    control-plane: controller-manager
  {{- include "sre-mutator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "sre-mutator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}