apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "hostaliases-injector.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "hostaliases-injector.labels" . | nindent 4 }}
spec:
  selfSigned: {}