apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hostaliases-injector.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hostaliases-injector
    app.kubernetes.io/part-of: hostaliases-injector
  {{- include "hostaliases-injector.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}